'use strict';

module.exports = function(req, res) {
  var absoluteNewLinkPath = [
    req.protocol,
    '://',
    req.hostname,
    ':',
    global.app.config.get('api:port'),
    global.app.config.get('api:prefix')
  ].join('');

  // Public links.
  var jsonAPIBody = {
    links: {
      "help": absoluteNewLinkPath + '/help',
      "signup": absoluteNewLinkPath + '/sign-up',
      "login": absoluteNewLinkPath + '/auth/login',
      "logout": absoluteNewLinkPath + '/auth/logout',
      "Usuario": absoluteNewLinkPath + "/usuario",
      "UsuarioHelp": absoluteNewLinkPath + "/usuario-help",
      "Area": absoluteNewLinkPath + "/area",
      "AreaHelp": absoluteNewLinkPath + "/area-help",
      "Sucursal": absoluteNewLinkPath + "/sucursal",
      "SucursalHelp": absoluteNewLinkPath + "/sucursal-help",
      //"Person": absoluteNewLinkPath + "/person",
      //"PersonHelp": absoluteNewLinkPath + "/person-help",
      "_": absoluteNewLinkPath + "/_",
      "_Help": absoluteNewLinkPath + "/_-help",
      "?": absoluteNewLinkPath + "/?",
      "?Help": absoluteNewLinkPath + "/?-help",
      "NoConformidad": absoluteNewLinkPath + "/noconformidad",
      "NoConformidadHelp": absoluteNewLinkPath + "/noconformidad-help",
      "Auditoria": absoluteNewLinkPath + "/auditoria",
      "Incidencia": absoluteNewLinkPath + "/incidencia",
      "QuejasReclamaciones": absoluteNewLinkPath + "/quejasreclamaciones",
      //"AuditoriaHelp": absoluteNewLinkPath + "/auditoria-help",
      "TipoNC": absoluteNewLinkPath + "/tiponc",
      "TipoNCdHelp": absoluteNewLinkPath + "/tiponc-help",
      //"Project": absoluteNewLinkPath + "/project",
      //"ProjectHelp": absoluteNewLinkPath + "/project-help",
      //"Config": absoluteNewLinkPath + "/config",
      //"ConfigHelp": absoluteNewLinkPath + "/config-help",
      //"Program": absoluteNewLinkPath + "/program",
      //"ProgramHelp": absoluteNewLinkPath + "/program-help",
      //"WebClient": absoluteNewLinkPath + "/web-client",
      //"WebClientHelp": absoluteNewLinkPath + "/web-client-help",
      //"Autodeploy": absoluteNewLinkPath + "/autodeploy",
      //"AutodeployHelp": absoluteNewLinkPath + "/autodeploy-help",
      //"Db": absoluteNewLinkPath + "/db",
      //"DbHelp": absoluteNewLinkPath + "/db-help",
      //"Snippets": absoluteNewLinkPath + "/snippets",
      //"SnippetsHelp": absoluteNewLinkPath + "/snippets-help",
      //"Tags": absoluteNewLinkPath + "/tags",
      //"TagsHelp": absoluteNewLinkPath + "/tags-help",
      //"ToDo": absoluteNewLinkPath + "/to-do",
      //"ToDoHelp": absoluteNewLinkPath + "/to-do-help",
      "Turista": absoluteNewLinkPath + "/turista",
      "TuristaHelp": absoluteNewLinkPath + "/turista-help",
      "Reserva": absoluteNewLinkPath + "/reserva",
      "ReservaHelp": absoluteNewLinkPath + "/reserva-help",
      "Mercado": absoluteNewLinkPath + "/mercado",
      "MercadoHelp": absoluteNewLinkPath + "/mercado-help",
      "Pais": absoluteNewLinkPath + "/pais",
      "PaisHelp": absoluteNewLinkPath + "/pais-help",
      "AgenciaViajes": absoluteNewLinkPath + "/agenciaviajes",
      "AgenciaViajesHelp": absoluteNewLinkPath + "/agenciaviajes-help",
      "Producto": absoluteNewLinkPath + "/producto",
      "ProductoHelp": absoluteNewLinkPath + "/producto-help",
      "ProdServicio": absoluteNewLinkPath + "/prodservicio",
      "ProdServicioHelp": absoluteNewLinkPath + "/prodservicio-help",
      "Norma": absoluteNewLinkPath + "/norma",
      "NormaHelp": absoluteNewLinkPath + "/norma-help",
      "Proceso": absoluteNewLinkPath + "/proceso",
      "ProcesoHelp": absoluteNewLinkPath + "/proceso-help",
    }
  };
  return res.status(200).json(jsonAPIBody); // OK.
};
