'use strict';

module.exports = function(req, res) {
  var absoluteNewLinkPath = [
    req.protocol,
    '://',
    req.hostname,
    ':',
    global.app.config.get('api:port'),
    global.app.config.get('api:prefix')
  ].join('');

  // Public links.
  var jsonAPIBody = {
    links: {
      "help": absoluteNewLinkPath + '/help',
      "signup": absoluteNewLinkPath + '/sign-up',
      "login": absoluteNewLinkPath + '/auth/login',
      "logout": absoluteNewLinkPath + '/auth/logout',
      "Usuario": absoluteNewLinkPath + "/usuario",
      "Roles": absoluteNewLinkPath + "/roles",
      "UsuarioHelp": absoluteNewLinkPath + "/usuario-help",
      "Area": absoluteNewLinkPath + "/area",
      "AreaHelp": absoluteNewLinkPath + "/area-help",
      "Sucursal": absoluteNewLinkPath + "/sucursal",
      "SucursalHelp": absoluteNewLinkPath + "/sucursal-help",
      "_": absoluteNewLinkPath + "/_",
      "_Help": absoluteNewLinkPath + "/_-help",
      "?": absoluteNewLinkPath + "/?",
      "?Help": absoluteNewLinkPath + "/?-help",
      "NoConformidad": absoluteNewLinkPath + "/noconformidad",
      "NoConformidadHelp": absoluteNewLinkPath + "/noconformidad-help",
      "Auditoria": absoluteNewLinkPath + "/auditoria",
      "Incidencia": absoluteNewLinkPath + "/incidencia",
      "QuejasReclamaciones": absoluteNewLinkPath + "/quejasreclamaciones",
      "Expediente": absoluteNewLinkPath + "/expediente",
      "ExpedienteHelp": absoluteNewLinkPath + "/expediente-help",
      "Dictamen": absoluteNewLinkPath + "/dictamen",
      "DictamenHelp": absoluteNewLinkPath + "/dictamen-help",
      "Acciones": absoluteNewLinkPath + "/acciones",
      "AccionesHelp": absoluteNewLinkPath + "/acciones-help",
      "Tareas": absoluteNewLinkPath + "/tareas",
      "TareasHelp": absoluteNewLinkPath + "/tareas-help",
      "Norma": absoluteNewLinkPath + "/norma",
      "NormaHelp": absoluteNewLinkPath + "/norma-help",
      "Proceso": absoluteNewLinkPath + "/proceso",
      "ProcesoHelp": absoluteNewLinkPath + "/proceso-help",
      "Indicadores": absoluteNewLinkPath + "/indicadores",
      "IndicadoresHelp": absoluteNewLinkPath + "/indicadores-help",
      "ObjetivosCalidad": absoluteNewLinkPath + "/objetivoscalidad",
      "ObjetivosCalidadHelp": absoluteNewLinkPath + "/objetivoscalidad-help",
      "Encuestas": absoluteNewLinkPath + "/encuestas",
      "EncuestasHelp": absoluteNewLinkPath + "/encuestas-help",
      "Categorias": absoluteNewLinkPath + "/categorias",
      "CategoriasHelp": absoluteNewLinkPath + "/categorias-help",
      "Preguntas": absoluteNewLinkPath + "/preguntas",
      "PreguntasHelp": absoluteNewLinkPath + "/preguntas-help",
      "Respuestas": absoluteNewLinkPath + "/respuestas",
      "RespuestasHelp": absoluteNewLinkPath + "/respuestas-help",
      "TipoNC": absoluteNewLinkPath + "/tiponc",
      "TipoNCHelp": absoluteNewLinkPath + "/tiponc-help",
      "TipoAC": absoluteNewLinkPath + "/tipoac",
      "TipoACHelp": absoluteNewLinkPath + "/tipoac-help",
      "Turista": absoluteNewLinkPath + "/turista",
      "TuristaHelp": absoluteNewLinkPath + "/turista-help",
      "Reserva": absoluteNewLinkPath + "/reserva",
      "ReservaHelp": absoluteNewLinkPath + "/reserva-help",
      "Mercado": absoluteNewLinkPath + "/mercado",
      "MercadoHelp": absoluteNewLinkPath + "/mercado-help",
      "Pais": absoluteNewLinkPath + "/pais",
      "PaisHelp": absoluteNewLinkPath + "/pais-help",
      "AgenciaViajes": absoluteNewLinkPath + "/agenciaviajes",
      "AgenciaViajesHelp": absoluteNewLinkPath + "/agenciaviajes-help",
      "Producto": absoluteNewLinkPath + "/producto",
      "ProductoHelp": absoluteNewLinkPath + "/producto-help",
      "ProdServicio": absoluteNewLinkPath + "/prodservicio",
      "ProdServicioHelp": absoluteNewLinkPath + "/prodservicio-help",
    }
  };
  return res.status(200).json(jsonAPIBody); // OK.
};
